### ISSUE TITLE
test/ppms/ missing from releases

### ISSUE THREAD

**Issue by juhp** [nh2/haskell-netpbm#2]
When building in Stackage NIghtly, the test fail...

I noticed all the test ppm's are missing from the releases on Hackage.
Not sure if that is the only problem though.

**Comment by bergmark** [comment]
The test-suite for this package has been disabled in stackage because of this issue. When a fix is published to hackage could you please send a PR to re-enable the tests to stackage (it's in the skipped-tests section) or ping me?

Thanks!

**Comment by nh2** [comment]
I've just pushed a commit to this effect; currently uploading the package ...

**Comment by juhp** [comment]
Thanks

**Comment by nh2** [comment]
http://hackage.haskell.org/package/netpbm-1.0.2

**Comment by nh2** [comment]
My last Hackage upload failed due to my bad connection, now it's uploaded.

**Comment by juhp** [comment]
Thanks I think it is already re-enabled in Stackage Nightly.
